apiVersion: v1
kind: Service
metadata:
  # The name must be equal to TcpDiscoveryKubernetesIpFinder.serviceName
  name: ignite
  # The name must be equal to TcpDiscoveryKubernetesIpFinder.namespaceName
  namespace: ignite
spec:
  type: LoadBalancer
  # Set externalTrafficPolicy to Cluster to expose the service on an external LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - name: rest
      port: 8080
      targetPort: 8080
    - name: sql
      port: 10800
      targetPort: 10800
    - name: thinclients
      port: 10900
      targetPort: 10900
    - name: thickclients-discovery
      port: 47500
      targetPort: 47500
  selector:
    # Must be equal to the label set for Ignite pods.
    app: ignite
